### ISSUE TITLE
Flames Nation - Cyrillic Characters Taking over Disqus window

### ISSUE THREAD

**Issue by MikeYEG** [nationnetwork/SiteFeedback#1]
**Describe the bug**
Some articles seem to have a different language than what is set in the disqus admin portal, and what is hard coded in the website.

**To Reproduce**
1. This article appears to have this issue: https://flamesnation.ca/news/top-50-flames-of-all-time-14-mark-giordano

**Expected behavior**
Be English.

**Screenshots**
![image](https://user-images.githubusercontent.com/26393053/193294032-16088351-a20e-4a0d-ad2d-09bc523f91c3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser Chrome
 - Version 106.0.5249.62

**Comment by MikeYEG** [comment]
Working with Disqus to determine root of issue. No resolution ETA.

**Comment by HALMacInnis** [comment]
Many forum members on Flames Nation have reported that the Cyrillic Disqus problem happens with Editorials only.

I'm unsure how your website is constructed, but if there is a different template (or block of code) used for Editorials, that could be the root of the problem.

**Comment by ivanfilippov** [comment]
@HALMacInnis Thank you for the extra detail, it has been very useful!

We've identified the cause of the issue and have a fix in place, it is undergoing internal testing and will be pushed into the live sites as soon as thats done.

**Comment by MikeYEG** [comment]
@HALMacInnis 
We've deployed a fix and don't see the issue occurring on the posts it was previously. Can you confirm on your end?

Regarding the framework we are using, it's called NextJS.

Thank you!

**Comment by HALMacInnis** [comment]
@MikeYEG 
The fix seems to have worked. I don't see any signs of the Cyrillic bug.

However, I did notice that the comments have been removed (reset with a new discussion thread?) in the affected articles, but given how few the number of comments were, I would consider it a non-issue. I do wonder if there is a way to preserve the comments, in the future, if a similar fix has to be deployed. Something to consider at least, moving forward.

**Comment by MikeYEG** [comment]
Hey @HALMacInnis 

Glad to hear it's working well!

Unfortunately, the comments are tied to the URL on which the disqus code is loaded on. By getting rid of the # in the URL, disqus sees it as a new thread/article. We will 100% keep this in mind going forward.

Appreciate the follow-up!
