### ISSUE TITLE
Jets Nation is not listed in the available Nation sites

### ISSUE THREAD

**Issue by HALMacInnis** [nationnetwork/SiteFeedback#10]
The link to Jets Nation ([https://jetsnation.ca](https://jetsnation.ca)) is missing in the listed Nation sites in the top menu and at the bottom links.

![no-jets-nation](https://user-images.githubusercontent.com/114796515/196353552-e8e58589-52e9-45a0-bd09-d9d0f12bf7c4.jpg)

**_Windows 10, Desktop, Firefox_**

I'm unfamiliar with the entirety of the Nation Network so it's possible that other sites are missing from the list as well.

**Comment by MikeYEG** [comment]
Hey @HALMacInnis !
Thanks for pointing that out, and yeah it was done intentionally! The list there is correct.

Thank you!
